### ISSUE TITLE
something wrong2: vap_table

### ISSUE THREAD

**Issue by Sjeff** [clyra/unifics#1]
Hi,

After installing via HACS and setting up the sensor i get this error:
![image](https://user-images.githubusercontent.com/11430228/111468120-82077a80-8725-11eb-9ed2-e5fcf5ed14ec.png)

I am using a USG with the following settings in the intergration:
![image](https://user-images.githubusercontent.com/11430228/111468336-b844fa00-8725-11eb-8472-d8349d56e613.png)

Best regards,
Jeffrey

**Comment by clyra** [comment]
Hi Jeffrey,

I never used a USG and I'm not sure if it should be compatible with the sensor. When you set the sensor thru the UI a test is made to verify that it's possible to login and if it's possible to retrieve the list of APs. Did you get past the UI and the sensor is created or you get stuck in the integrations settings?

Do you have only the USG, but no controller?

**Comment by clyra** [comment]
ah... as it seems to be, the USG is not a unifi controller:

 https://community.ui.com/questions/USG-as-unifi-Controller/4e34bbee-6038-4fd1-b928-e18f4e888d73

**Comment by Sjeff** [comment]
Yes i am using a controller running in docker.
Version 6.0.45 from jacobalberty

because you made a checkbox for a udm i mentioned the USG.

**Comment by clyra** [comment]
ah, ok. So my best guess is that the controller list the USG as a device, but the USG itself doesnt have the same kind of information. I think I have to make some kind of test while reading information from them. I will work on a fix.

**Comment by Sjeff** [comment]
Thanks @clyra a lot more data is showing:
![image](https://user-images.githubusercontent.com/11430228/111517287-310f7a80-8755-11eb-94fb-829dfccb8b71.png)

**Comment by clyra** [comment]
How familiar are you with python? If possible, i'd like a dump of the json returned by the unificontrol library, so I can find a better fix this.

**Comment by Sjeff** [comment]
not really familiar but i can run some scripts or commands if you can provide them?

**Comment by clyra** [comment]
ok, let's try this:

1) create the python enviroment with the following comands:
```
$ python3 -mvenv unificontrol
$ source unificontrol/bin/activate
$ pip install -e git+https://github.com/nickovs/unificontrol.git@udm-support#egg=unificontrol
```
2) create the dump_json.py with the following content (edit the ip/password):
```
import unificontrol
import json
client = unificontrol.UnifiClient(host='192.168.0.xx',
                                  username='admin',
                                  password='yourpassword',
                                  site='default',
                                  server_type=unificontrol.UnifiServerType.CLASSIC)
print(json.dumps(client.list_devices(), indent=2))
```

3) run it:
```
$ python dump_json.py
```
or
```
$ python dump_json.py > output.txt
```

4) Maybe you want to edit the output.txt as it will contain devices names/ip addresses/mac address, before send.

**Comment by Sjeff** [comment]
Can you give me your email adres?
i have the file ready

**Comment by clyra** [comment]
sure. please send to poplyra [at] gmail.com.

**Comment by Sjeff** [comment]
you should have an email.
i hope it helps :)

**Comment by Sjeff** [comment]
Closing this issue because you have fixed the problem last time :) 
Thank you!
