### ISSUE TITLE
Platform error sensor.unifics - Integration 'unifics' not found.

### ISSUE THREAD

**Issue by boomam** [clyra/unifics#18]
Latest update causes this error in configuration validation, preventing restart of Home Assistant:  

> Platform error sensor.unifics - Integration 'unifics' not found.  

Nothing has changed since since the update.
&nbsp;  

Current Config file for unifics - 
````
#################################################################
## Sensor Configuration
## Unifi Counter
#################################################################

# https://github.com/clyra/unifics

# Unifi Counter
  - platform: unifics
    name: "UniFi Wi-Fi Client Count Sensor"
    host: !secret unifi_host
    port: !secret unifi_port
    username: !secret unifi_username
    password: !secret unifi_password
    site: !secret unifi_site
    verify_ssl: False
    udm: False
````

Sensor reference in configuration.yaml -   

````
# Sensor Configuration
sensor: !include_dir_merge_list config_files/sensor/
````

I currently have the sensor file renamed so the rest of HA works, but im happy to do whatever testing is needed to diagnose.  
&nbsp;  
Thanks!

**Comment by boomam** [comment]
Interesting, setting HACS to redownload the app appears to have resolved it....testing more....

**Comment by clyra** [comment]
hm... I changed the required library used by the integration. My guess is that when you updated the integration that library wasn't present/downloaded and the redownload fixed that.

**Comment by boomam** [comment]
Not sure - I mean I'm happy that it was a simple enough fix, and I guess its useful for if anyone googles the error, so....win win? :-p  
Seems fine still though, so I'll close the issue as resolved.
