### ISSUE TITLE
No devices showing in Sensor Card

### ISSUE THREAD

**Issue by Ragetti13** [clyra/unifics#19]
Hi,

The integration appears to be set up correctly but is not showing on the overview within the Sensor Card. Any advice would be appreciated.

<img width="668" alt="Screenshot 2022-02-16 at 09 45 11" src="https://user-images.githubusercontent.com/66558012/154238199-004bb287-6bdb-4334-934d-ff1f55eadc6f.png">

**Comment by clyra** [comment]
The status of the sensor should be the total number of devices (5 in your case, i guess), but somehow it's saying is zero. Somehow it is failing to account all of them. One know issue is if you have a unnamed AP, may you try to name the second AP? Also, look into the logs as there should be a error there.

**Comment by clyra** [comment]
hi,

hm... that's odd. so it seems that you have something that looks like a AP but doesnt have a mac address? I will put some kind of test to avoid that, but may you tell me a bit more about your devices?

**Comment by Ragetti13** [comment]
I have attached the latest screenshot of how the sensor looks:
<img width="394" alt="Screenshot 2022-02-17 at 13 05 38" src="https://user-images.githubusercontent.com/66558012/154487667-bca9ac9a-7d08-4329-85a7-a099aadf61c9.png">

My setup is all Ubiquiti:

UDM with a 24port switch (US-24-G1) and a single AP (U6-Lite).

Let me know if you need any additional info

**Comment by clyra** [comment]
Hi,

New version out. Please, try it.

**Comment by Ragetti13** [comment]
All working now once i redownloaded and reinstalled the integration
