### ISSUE TITLE
Sensor error but working output

### ISSUE THREAD

**Issue by mn-box** [clyra/unifics#21]
I am getting below error using below sensor, the sensor works but don't like errors in my log ;-)
## Unify sensor
  - platform: unifics
    name: Unifi counter
    host: XX
    port: XX
    username: X
    password: XX
    site: 'default'
    verify_ssl: 'False'
    udm: 'True'

2022-08-17 08:00:09 ERROR (MainThread) [custom_components.unifics.sensor] Error while trying to update sensor: can only concatenate str (not "NoneType") to str

**Comment by myopenflixr** [comment]
I am also receiving this error. Any solutions found?

**Comment by clyra** [comment]
Hi

Sorry for the long reply time. There's a few corner cases when the unifi controller doesn't return a expected value, like the AP  name. To solve this, we need to look into the returned json from the pyunifi library. I will write a script to do that and we may continue after that.

**Comment by clyra** [comment]
Hi, 

May you try again? i did a update to the code.

**Comment by mn-box** [comment]
Super, working!
