### ISSUE TITLE
Migration from HomeAssistant OS to Docker installation 

### ISSUE THREAD

**Issue by michelnet** [clyra/unifics#22]
Hi,

I migrated my installation from HomeAssistant OS to a Docker installation. Now i have follow error: 

Platform error sensor.unifics - Requirements for unifics not found: ['pyunifi@git+https://github.com/finish06/pyunifi.git#egg=pyunifi'].

Did you know how how can i solve this?

Regards

Thomas

**Comment by clyra** [comment]
Hi,

The integration need to download/install a external library. HA should do this. Are you running the last version of the integration?

**Comment by michelnet** [comment]
Hi, i found the failer, i used the linuxserver.io image and not the office one, after the change everting works fine :-)

**Comment by clyra** [comment]
Hi! Glad to hear that. The folks at linuserver usually do a good a job... I wonder what they missed on this image.
