### ISSUE TITLE
Sensor Not Counting

### ISSUE THREAD

**Issue by JDogg016** [clyra/unifics#23]
I installed the sensor and it shows a count of 0 (it should be 200) and has the following error in the log:

Logger: custom_components.unifics.sensor
Source: custom_components/unifics/sensor.py:241 
Integration: Unifi Counter Sensor 
First occurred: 10:45:42 AM (30 occurrences) 
Last logged: 10:53:06 AM

Error while trying to update sensor: can only concatenate str (not "NoneType") to str
ap_name: AP Barn Outside AP, client_essid: iOT
ap_name: AP Barn Outside AP, client_essid: Sibenik

**Comment by clyra** [comment]
Hi,

this usually happens when there's missing info, like Ap name.  I will look into this.

**Comment by clyra** [comment]
Is there anything else in the logs?

**Comment by JDogg016** [comment]
***@***.***

What I find odd about the ‘counter’ is that sensors appear and disappears just as fast.  There are no logs that I know how to fetch to show the sensor count going from 0 to 200 and then back to 0.  The only additional log I found follows the earlier posted log:

***@***.***

Let me know how I may further help.

From: clyra ***@***.***>
Date: Wednesday, March 1, 2023 at 9:21 AM
To: clyra/unifics ***@***.***>
Cc: JDogg016 ***@***.***>, Author ***@***.***>
Subject: Re: [clyra/unifics] Sensor Not Counting (Issue #23)

Is there anything else in the logs?

**Comment by spamsal** [comment]
Can confirm having the same issues. Not all connections are logging and as @JDogg016 mentioned, the count jumps up and down randomly.

**Comment by clyra** [comment]
Hi,

I did a small update to the sensor. Hopefully it will either fix the problem or log all the info I need to fix it. May you update/try the new version?

**Comment by JDogg016** [comment]
Should I see the update in HA or would you suggest I uninstall then reinstall?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by clyra** [comment]
Hi,

I did upgrade the version number, but not sure if you should see it change in hacs. You may just copy the sensor.py, or if it's more convenient, reinstall.

**Comment by JDogg016** [comment]
Is it Version 7bb3a9f?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by JDogg016** [comment]
Remove the integration. Remove the installation instance and reloaded it completely. Reinstalled the integration and now we received the following error in the logs.

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/unifics/sensor.py:224
Integration: Unifi Counter Sensor
First occurred: 5:56:00 PM (1 occurrences)
Last logged: 5:56:00 PM

Error unloading entry unifics for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 539, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 137, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 183, in async_unload_entry
    await platform.async_reset()
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 731, in async_reset
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 829, in async_remove
    await self.async_will_remove_from_hass()
  File "/config/custom_components/unifics/sensor.py", line 224, in async_will_remove_from_hass
    self.coordinator.async_remove_listener(self.async_write_ha_state)
AttributeError: 'DataUpdateCoordinator' object has no attribute 'async_remove_listener'


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by clyra** [comment]
Hi,

Are you using the yaml or the ui configuration? This error seems to be triggered while removing the integration, but only when you did the configuration thru the UI. I did a ugly fix for now, but will investigate further.

**Comment by JDogg016** [comment]
Ui

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by JDogg016** [comment]
Installed update. Still reports 0 as the count.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by clyra** [comment]
Ok,

Please look the logs.

**Comment by JDogg016** [comment]
I apologize, I thought I sent these last week.  There are two logs, the first is too long to post so I truncated it:

Logger: custom_components.unifics.sensor
Source: custom_components/unifics/sensor.py:248
Integration: Unifi Counter Sensor
First occurred: March 17, 2023 at 2:14:20 PM (9800 occurrences)
Last logged: 7:50:13 AM

`raw data wlans: [{'_id': '627ce2b21d95f10637af9d15', 'networkconf_id': '627ce1a61d95f10637af9c99', 'x_passphrase': 'Helen143!', 'ap_group_ids': ['62f84fa60de28b535dca3b18'], 'name': 'Sibenik', 'setting_preference': 'manual', 'site_id': '627ce1971d95f10637af9c84', 'bss_transition': True, 'dtim_mode': 'default', 'dtim_6e': 3, 'dtim_na': 3, 'dtim_ng': 1, 'enabled': True, 'fast_roaming_enabled': True, 'group_rekey': 0, 'hide_ssid': False, 'is_guest': False, 'l2_isolation': False, 'b_supported': False, 'mac_filter_enabled': True, 'mac_filter_list': ['a2:c1:d1:69:79:08', '78:fd:94:6a:25:91', '6e:e1:14:01:48:1c'], 'mac_filter_policy': 'deny', 'mcastenhance_enabled': True, 'minrate_setting_preference': 'manual', 'minrate_na_enabled': True, 'minrate_na_advertising_rates': False, 'minrate_na_data_rate_kbps': 9000, 'minrate_ng_enabled': True, 'minrate_ng_advertising_rates': False, 'minrate_ng_data_rate_kbps': 2000, 'no2ghz_oui': False, 'wpa_enc': 'ccmp', 'pmf_mode': 'disabled', 'proxy_arp': False, 'radius_das_enabled': False, 'radius_mac_auth_enabled': False, 'radius_macacl_format': 'none_lower', 'security': 'wpapsk', 'uapsd_enabled': False, 'wlan_bands': ['2g', '5g'], 'wpa3_enhanced_192': False, 'wpa3_fast_roaming': False, 'wpa3_support': False, 'wpa3_transition': False, 'wpa_mode': 'wpa2', 'usergroup_id': '627ce1a61d95f10637af9c9a', 'iapp_enabled': True, 'x_iapp_key': 'f1b157d6e62c6fbddc202f9be82f89da', 'wlan_band': 'both', 'bc_filter_list': ['74:ac:b9:13:b0:43', '82:ef:28:43:63:f5', 'd4:90:9c:e6:59:18', 'd4:90:9c:e9:ff:f8', 'd4:90:9c:ec:32:6d', 'd4:90:9c:ee:6b:97', '50:de:06:7b:54:ee', 'ec:a9:07:27:3c:5a', '40:cb:c0:b7:16:b5', 'ec:a9:07:06:79:ee', 'd4:a3:3d:5d:96:6f', 'c8:69:cd:30:0a:d9', '04:99:b9:7a:81:46', 'd4:90:9c:ea:78:03', 'd4:a3:3d:5e:ec:99', '58:d3:49:50:0e:6b', '58:d3:49:ee:87:b9', 'd0:81:7a:e2:de:00', '4e:9c:7c:b0:a1:d2', '56:db:13:38:ca:91', '04:99:b9:7e:fe:b2', 'ba:4d:e6:84:00:f8', '04:99:b9:82:5f:46', 'c4:91:0c:b6:b0:65', '32:ed:ed:9a:40:86', '94:9f:3e:b3:b2:6a', 'f0:f6:c1:9a:34:f7', '48:a6:b8:32:9e:d7', 'f0:f6:c1:9a:6a:76', '48:a6:b8:e5:f9:32', '54:2a:1b:e3:80:bb', '78:28:ca:0e:31:dc', '78:28:ca:0e:32:4a', '94:9f:3e:d3:59:b3', '5c:aa:fd:40:9c:0a', '94:9f:3e:cb:6f:ac', '94:9f:3e:22:58:52', '54:2a:1b:21:e0:64', '94:9f:3e:bb:3d:4e', '78:28:ca:0e:32:32', 'f4:34:f0:0e:03:a2', 'c8:69:cd:2f:57:70', '54:2a:1b:e3:80:54', '78:28:ca:0e:31:94', 'f0:f6:c1:07:4a:64', '78:28:ca:7a:e9:c4', '94:96:3e:d3:59:63', '78:fd:94:6a:25:91', '88:63:df:ca:80:0b', 'ae:8c:1d:d5:e7:db', '04:99:69:82:5f:46', 'c6:7a:12:d2:63:e8', 'd0:03:46:01:9e:24', '6e:58:2e:9a:39:d7', 'ba:56:af:1d:52:91', '0a:b6:30:76:81:b6', '04:99:69:7e:fe:b2', 'd6:52:97:2d:7f:2e', '64:d2:c4:db:ac:db', '8a:21:86:e1:54:86', '04:99:b9:b2:43:ec', 'e0:2b:96:b0:e9:c5', '40:cb:c0:b6:1a:7e', 'ec:a9:07:24:7b:66', 'b4:b5:b6:e4:f4:09'], 'sae_groups': [], 'sae_psk': [], 'schedule': [], 'schedule_with_duration': [], 'optimize_iot_wifi_connectivity': False, 'bc_filter_enabled': True}, {'_id': '627ce68f1d95f10637afa3e0', 'ap_group_ids':`


AND the second:

This error originated from a custom integration.

Logger: custom_components.unifics.sensor
Source: custom_components/unifics/sensor.py:78
Integration: Unifi Counter Sensor
First occurred: March 17, 2023 at 3:53:05 PM (7 occurrences)
Last logged: 6:32:35 AM

Unexpected error fetching sensor data: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyunifi/controller.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyunifi/controller.py", line 139, in _read
    return self._jsondec(response.text)
  File "/usr/local/lib/python3.10/site-packages/pyunifi/controller.py", line 117, in _jsondec
    obj = json.loads(data)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 195, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/unifics/sensor.py", line 78, in async_update_data
    data["clients"] = await hass.async_add_executor_job(control.get_clients)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyunifi/controller.py", line 270, in get_clients
    return self._api_read("stat/sta")
  File "/usr/local/lib/python3.10/site-packages/pyunifi/controller.py", line 142, in _api_read
    return self._read(self._api_url() + url, params)
  File "/usr/local/lib/python3.10/site-packages/pyunifi/controller.py", line 38, in wrapper
    raise APIError(err)
pyunifi.controller.APIError: Expecting value: line 1 column 1 (char 0)

**Comment by clyra** [comment]
Hi all,

New version out.

**Comment by clyra** [comment]
Hi all,

I will close this issue as the last fixes seems to work :-). Feel free to reopen as needed.
