### ISSUE TITLE
2023.6 InsecureRequestWarning

### ISSUE THREAD

**Issue by woodmj74** [clyra/unifics#25]
Since 2023.6 I am receiving the following warnings in the logs from this integration:

```
2023-06-08 13:30:35.760 WARNING (SyncWorker_8) [py.warnings] /usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.0.10'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
```

I have disabled all integrations associated to unifi and tracked them back one by one to confirm this is generating this error. 
I am using a cloudkey as the controller and as such haven't installed any certs etc. on the machine. Prior to 2023.6 this was working without errors.

Any suggestions would be gratefully received to resolved these warnings.

**Comment by clyra** [comment]
Hi,

This is annoying... and I couldnt find a way to prevent it. But you can make HA ignore that. You may follow that link or as I use it:
```
logger:
  default: info
  logs:
    requests.packages.urllib3.connectionpool: critical
```

**Comment by woodmj74** [comment]
okay thanks @clyra - appreciate you looking into it. Seems to be fairly wide spread over a number of integrations (both core and custom) so hopefully someone will find a way of tackling it globally. 
:-)

**Comment by woodmj74** [comment]
I'm not sure if this is of any help?

https://github.com/home-assistant/core/issues/94243#issuecomment-1586672393

**Comment by clyra** [comment]
Hi @woodmj74 

New version is out with the same "fix" used in the proxmox integration. Seems to work with a minor issue: it still log a warning when the integration starts, but goes silent after that. Not sure if we can fix that because it seems to be done by HA.

**Comment by woodmj74** [comment]
Hi @clyra - thanks, appreciate you looking into this. 

Initial testing looks good, as you say get the initial message but then silent so happy with that. Will close and many thanks again.

**Comment by plouf34** [comment]
Any news reagring this issue. I've the same error in HA: 
`/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings warnings.warn(`

**Comment by nicx** [comment]
+1
