### ISSUE TITLE
Error while trying to update clients: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by jkfranks9** [clyra/unifics#26]
I'm seeing the following error periodically:

`
2023-08-05 08:41:45.277 INFO (MainThread) [custom_components.unifics.sensor] Error while trying to update clients: 'str' object has no attribute 'get'
2023-08-05 08:41:45.280 INFO (MainThread) [custom_components.unifics.sensor] client: timestamp
2023-08-05 08:41:45.317 ERROR (MainThread) [custom_components.unifics.sensor] raw data clients: {'timestamp': '2023-08-05T12:41:45Z', 'status': 500, 'error': 'Internal Server Error', 'path': '/api/s/default/stat/sta'}
`

Note that the "raw data aps" and "raw data wlans" logs are quite large, contain sensitive data, and don't appear to be relevant to this problem. However, if you need them I can attempt to scrub the data.

I'm using version 0.2.3, HA version is 2023.8.1, Supervisor is 2023.07.1, OS is 10.4

Also, I needed to fix several _LOGGER calls to get the above log output. I'll open a separate issue for that.

**Comment by clyra** [comment]
Sometimes we discover a object that doesnt looks like it should and this may break the parsing done by the sensor. Usually when we expect to see some property and there's none, like client name or mac. I built some checks in the code, but there's still something missing. We may fix the logger and hopefully it will provide more information on what's breaking.

**Comment by clyra** [comment]
Hi, 

May you update the integration? hopefully it will log the client (device) that was triggering the problem.

**Comment by jkfranks9** [comment]
Thanks for the quick response. Things are crazy today, but I will give it a try as soon as possible.

**Comment by jkfranks9** [comment]
The logs are basically the same as noted above:
`
2023-08-06 19:03:06.773 ERROR (MainThread) [custom_components.unifics.sensor] Error while trying to update clients: 'str' object has no attribute 'get'
2023-08-06 19:03:06.783 ERROR (MainThread) [custom_components.unifics.sensor] client: timestamp
2023-08-06 19:03:06.785 ERROR (MainThread) [custom_components.unifics.sensor] raw data clients: {'timestamp': '2023-08-06T23:03:06Z', 'status': 500, 'error': 'Internal Server Error', 'path': '/api/s/default/stat/sta'}
`

The client is identified as "timestamp", which makes sense given the raw data returned, which appears to just be an error message. 

Since you do catch this error and report it, and I'm assuming it's a temporary problem (because the data reported by this integration are correct), I can live with it as is, and just filter out the messages from the HA log.

But of course it's your call, if you think there's something else going on, or want to handle it differently.

**Comment by clyra** [comment]
Hm... I would like to better handle those odd cases. The unifi controller return a list of clients, but it seems that one of them is causing a error 500 on the unifi api! Are you sure that the reported values are right? I would expected that the wired or clients per ap or clients per essid should be off by at least 1.

**Comment by jkfranks9** [comment]
I added an automation to trigger on one of the unifi_counter attributes ("wired") and write a log message showing the state and the relevant attributes whenever it changes. Here are the error messages from sensor.py (I've removed the preambles for clarity):

`
Error while trying to update clients: 'str' object has no attribute 'get'
`
`
client: timestamp
`
`
raw data clients: {'timestamp': '2023-08-11T16:21:13Z', 'status': 500, 'error': 'Internal Server Error', 'path': '/api/s/default/stat/sta'}
`

And here is the message from my automation (I did not use the actual names for all attributes in the message):

`
JKF: total: 70; wired: None; wifi: 0; guest: 0; udm: 0; u6: 0
`

So for some reason, when the error occurs all the counter attributes go to 0, except for "wired" which becomes None.

I don't see any way to find out if there's a certain client causing the problem. This error hits randomly, then fixes itself within a few seconds. So every time I compare the values from the integration with the values shown in my router, everything matches.

Not sure where to go from here.

**Comment by clyra** [comment]
I guess my previous understanding was wrong. The unifi controller itself is throwing a error 500. I think the integration should just ignore this as a invalid response, so I should put a test to see if the response is valid and then parse it, instead of parsing it and throw a error.

**Comment by jkfranks9** [comment]
Hi, just checking if there's an update or ETA on a fix. Thanks.

**Comment by clyra** [comment]
i think the last update fixed that.
