### ISSUE TITLE
Add "wired" as an attribute

### ISSUE THREAD

**Issue by Berserkir-Wolf** [clyra/unifics#7]
First off, wicked replacement for the old "my_unifi" custom component - dropped in and mostly worked right away.

Is there any way to add the ability to see switches and wired clients? 
When adding a unifi switch into the mix the old my_unifi component would break out 'wired' clients as a separate counter as well.

**Comment by clyra** [comment]
Hi,

hm... you are right. But should be easy to add this again. Gimme a couple of days.

**Comment by clyra** [comment]
well... it took a lot more than a couple of days, but it's done now.

**Comment by thundergreen** [comment]
Did U push already? Don't see it in hacs

**Comment by thundergreen** [comment]
Ok I'm with stupid...is there

**Comment by clyra** [comment]
small update online. Now it will show (sorted)  APs and WLANS with 0 clients.

**Comment by thundergreen** [comment]
Looks and works pretty good .opened a new issue with features request.if
you have time and mood ..you can have a look

clyra ***@***.***> schrieb am So., 9. Jan. 2022, 22:12:

**Comment by clyra** [comment]
closing this one too.

**Comment by Berserkir-Wolf** [comment]
Beautiful. Thank you very much for this one, @clyra
