### ISSUE TITLE
Loading configuration flow

### ISSUE THREAD

**Issue by Sjeff** [clyra/unifics#9]
I just updated HA to 2021.5.2 dont know what changed exactly but im receiving this error:

Error occurred loading configuration flow for integration unifics: cannot import name 'UnifiServerType' from 'unificontrol' (/usr/local/lib/python3.8/site-packages/unificontrol/__init__.py)

**Comment by Berserkir-Wolf** [comment]
Have you updated unifics? New version adjusts how the module gets loaded.

**Comment by clyra** [comment]
Hi, try again, plz. Just merged the PR.

**Comment by Sjeff** [comment]
Thanks @clyra and @Berserkir-Wolf working fine again :)

**Comment by NicholasBrody** [comment]
Still get the error.
Error occurred loading configuration flow for integration unifics: cannot import name 'UnifiServerType' from 'unificontrol' (/usr/local/lib/python3.8/site-packages/unificontrol/init.py)
I removed it from HACS rebootted HomeAssistant and add it back with no result then I removed it again and copied it myself to custom_components but also with no luck.
 Please let me know how to use this correct

**Comment by Berserkir-Wolf** [comment]
Hi @NicholasBrody, we're working with the person who maintains that library at present - it's being rewritten to support the Unifi Dream Machine. 
For some reason, ubiquiti has changed some of the methods for interacting with the API. 
What does your requirements line look like in manifest.json?

**Comment by NicholasBrody** [comment]
Hi @Berserkir-Wolf  thanks for your reaction,
this is my manifest.json: `{
  "domain": "unifics",
  "name": "Unifi Counter Sensor",
  "config_flow": true,
  "documentation": "https://www.home-assistant.io/integrations/unifics",
  "requirements": ["unificontrol@git+https://github.com/nickovs/unificontrol.git@udm-support#egg=unificontrol"],
  "dependencies": [],
  "codeowners": ["@clyra"],
  "version": "0.1.3",
  "iot_class": "local_polling"
}`
